var game_file_list = [
	"views/ViewBase.js",
	"DataCenter.js",
	"jinglibs/notice/Notice.js",
	"views/battle/Block.js",
	"Util.js",
	"jinglibs/notice/NoticeManager.js",
	"vo/NoticeCode.js",
	"views/BitmapNumber.js",
	"views/ShareView.js",
	"views/TipsView.js",
	"views/battle/Boss.js",
	"views/battle/BossHP.js",
	"LoadingUI.js",
	"views/ResultView.js",
	"views/StartView.js",
	"views/battle/Battle.js",
	"Roushan.js"
];